#include <iostream>
#include <stdio.h>
#include <conio.h>
#include <stdlib.h>
#include <time.h>
#include <Windows.h>
using namespace std;

bool quitting = false;

DWORD WINAPI InputThread(LPVOID data);

int main()
{
    srand((unsigned)time(NULL));
    HANDLE threadHandle;
    DWORD threadID;

    threadHandle = CreateThread(NULL, 0, InputThread, (LPVOID)1, 0, &threadID);

    while (!quitting)
    {

        system("CLS");
        printf("                                                                                                   \n");
        printf("                                       TTTTTTTTTTT                                                 \n");
        printf("                              TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                      \n");
        printf("                       TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                 \n");
        printf("                    TTTTTTTTTTTTTTTTTGGGGGGGGGGGGGGGTTTTTTTTTTTTTTTTT                              \n");
        printf("                  TTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTTTTTTTTT                            \n");
        printf("                 TTTTTTTTGGGGGGGGGGGGGGG@@@@@@@@@GGGGGGGGGGGGGGGTTTTTTTT                           \n");
        printf("                 TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                           \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGTTTTTTT                          \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                         \n");
        printf("               TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGGGGTTTTTTTT                          \n");
        printf("               TTTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@GGGGGGGGGGGGGTTTTTTTT                          \n");
        printf("                TTTTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGTTTTTTTTTT                           \n");
        printf("                TTTTGGGGGGGGG!!!!!!!!!GGG@@@@@@GGG!!!!!!!!!!GGGGGGGGTTTT                           \n");
        printf("                TTTGGG!!!!!!!!!!!''''!!!GGGGGGGG!!!''''!!!!!!!!!!GGGGTTT                           \n");
        printf("                 'TGG!!!!!!!''''''''''!!!GGGGGG!!!'''''''''!!!!!!!GGGT'                            \n");
        printf("                 'TGG!!!!!'''''''''''''!!GG@@GG!!''''''''''''!!!!!!!GG'                            \n");
        printf("                 ''TG@G!!!!''''''''''''!!!@@@@G!!'''''''''''!!!!!!G@GT                             \n");
        printf("                   TG@G!!!!!!'''''''''!!!!@'@'@!!!''''''''!!!!!!!!G@GT                             \n");
        printf("                   'TG@G!!!!!!!!!!!!!!GGG@''@''@GGG!!!!!!!!!!!!!!!G@GT'                            \n");
        printf("                  ''TG@G!!!!!!!!GGGGGGGGG@''G''@GGGGGGGGGG!!!!!!!!G@GT''                           \n");
        printf("                '''TTTG@@G!GGGGGGGGGGGTT@'''!'''@GGGGGGGGGGGGGGG!G@@GTTT'''                        \n");
        printf("               TTTGGGTTTGGGGGGGGTTTTTTGG@'''''''@GGTTTTGGGGGGGGGGGTTTGGGTTTT                       \n");
        printf("                TG@GTT!!TGGGGGTTTT!!!!TTG'''!'''GTTTTTTTTGGGGGGGT!!TTG@GT                          \n");
        printf("                  TTT!!!!!GG@GGTTT!!!!TT@'''T'''@GTTTTTGGGGG@GG!!!!!TTT                            \n");
        printf("                    ''!TGG@@@@@GGGT!!TTTTG''G''@GGTTGGGGGG@@@@@@GGT''                              \n");
        printf("                      TTTGGG@@''''G@GTTTGGGT@GGGGGGGGG''''@@GGGTTT                                 \n");
        printf("                       TTGGGG@''  !GGTTTGGGGGGGGGTTTGG!  ''@GGGGTT                                 \n");
        printf("                       TTGGGG@''  TGTTTGGGGGGGGGGGTTTGT  ''@GGGGTT               T                 \n");
        printf("                       TTTGGG@!'' GTG@T@@T@@T@@T@@T@GTG ''!@GGGTTT           TTTTTTT               \n");
        printf("                        TTGGG@G!' GTGG!G@T@@G@@T@G!GGTG '!G@GGGTT          TTTTTTTT!               \n");
        printf("                        TTGGG@G@@@@@@@TTGGT@G@TGGTT@@@@@@@G@GGGTT         GTTTT                    \n");
        printf("                    G@@@@@@@@@@GG!!TTGGGGG@@GGTG@@TGTT!!GG@@@@@@@@@G    GG'           !!!!!!       \n");
        printf("          @@@@@@@@@@@G TTGGG@GGGTT!!TTGGGGG@GGTG@GGTT!!TTGGG@GGGTTG@@@@@@@        GG!!!!!!!!!'!!   \n");
        printf("      @@@@GG           TGG@@GGTTGTT!!TTGGGGGGGGGGGTT!!TTGTTGG@@GGT        @@@@@@GGG!!!!!!!!'!''!!  \n");
        printf("                        '!TTGGGTTTTT!!TTGGGGGGGGGTT!!TTTTTGGGTT!'             GGGTTTTTTTTTT!'!!'!! \n");
        printf("                            TTTTTGGTT!TTTTTGGGTTTTT!TTGGTTTTT                  GTTTTTTTTTTT'TT'!!! \n");
        printf("                                TTGTTTTTTTTTTTTTTTTTTTGTT                        TTTTTTTTTT!''!!!! \n");
        printf("                                   TTTTTGGTTTTTGGTTTTT                               !!!!!!!'!!!   \n");
        printf("                                        TGGGTGGGT                                       !!!!!!     \n");
        printf("                                                                                                   \n");
        Sleep(300);
        system("CLS");
        printf("                                                                                                   \n");
        printf("                                       TTTTTTTTTTT                                                 \n");
        printf("                              TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                      \n");
        printf("                       TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                 \n");
        printf("                    TTTTTTTTTTTTTTTTTGGGGGGGGGGGGGGGTTTTTTTTTTTTTTTTT                              \n");
        printf("                  TTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTTTTTTTTT                            \n");
        printf("                 TTTTTTTTGGGGGGGGGGGGGGG@@@@@@@@@GGGGGGGGGGGGGGGTTTTTTTT                           \n");
        printf("                 TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                           \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGTTTTTTT                          \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                         \n");
        printf("               TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGGGGTTTTTTTT                          \n");
        printf("               TTTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@GGGGGGGGGGGGGTTTTTTTT                          \n");
        printf("                TTTTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGTTTTTTTTTT                           \n");
        printf("                TTTTGGGGGGGGG!!!!!!!!!GGG@@@@@@GGG!!!!!!!!!!GGGGGGGGTTTT                           \n");
        printf("                TTTGGG!!!!!!!!!!!''''!!!GGGGGGGG!!!''''!!!!!!!!!!GGGGTTT                           \n");
        printf("                 'TGG!!!!!!!''''''''''!!!GGGGGG!!!'''''''''!!!!!!!GGGT'                            \n");
        printf("                 'TGG!!!!!'''''''''''''!!GG@@GG!!''''''''''''!!!!!!!GG'                            \n");
        printf("                 ''TG@G!!!!''''''''''''!!!@@@@G!!'''''''G'''!!!!!!G@GT                             \n");
        printf("                   TG@G!!!!!!'''''''''!!!!@'@'@!!!''''''''!!!!!!!!G@GT                             \n");
        printf("                   'TG@G!!!!!!!!!!!!!!GGG@''@''@GGG!!!!!!!!!!!!!!!G@GT'                            \n");
        printf("                  ''TG@G!!!!!!!!GGGGGGGGG@''G''@GGGGGGGGGG!!!!!!!!G@GT''                           \n");
        printf("                '''TTTG@@G!GGGGGGGGGGGTT@'''!'''@GGGGGGGGGGGGGGG!G@@GTTT'''                        \n");
        printf("               TTTGGGTTTGGGGGGGGTTTTTTGG@'''''''@GGTTTTGGGGGGGGGGGTTTGGGTTTT                       \n");
        printf("                TG@GTT!!TGGGGGTTTT!!!!TTG'''!'''GTTTTTTTTGGGGGGGT!!TTG@GT                          \n");
        printf("                  TTT!!!!!GG@GGTTT!!!!TT@'''T'''@GTTTTTGGGGG@GG!!!!!TTT                            \n");
        printf("                    ''!TGG@@@@@GGGT!!TTTTG''G''@GGTTGGGGGG@@@@@@GGT''                              \n");
        printf("                      TTTGGG@@''''G@GTTTGGGT@GGGGGGGGG''''@@GGGTTT                                 \n");
        printf("                       TTGGGG@''  !GGTTTGGGGGGGGGTTTGG!  ''@GGGGTT                                 \n");
        printf("                       TTGGGG@''  TGTTTGGGGGGGGGGGTTTGT  ''@GGGGTT               T                 \n");
        printf("                       TTTGGG@!'' GTG@T@@T@@T@@T@@T@GTG ''!@GGGTTT           TTTTTTT               \n");
        printf("                        TTGGG@G!' GTGG!G@T@@G@@T@G!GGTG '!G@GGGTT          TTTTTTTT!               \n");
        printf("                        TTGGG@G@@@@@@@TTGGT@G@TGGTT@@@@@@@G@GGGTT         GTTTT                    \n");
        printf("                    G@@@@@@@@@@GG!!TTGGGGG@@GGTG@@TGTT!!GG@@@@@@@@@G    GG'           !!!!!!       \n");
        printf("          @@@@@@@@@@@G TTGGG@GGGTT!!TTGGGGG@GGTG@GGTT!!TTGGG@GGGTTG@@@@@@@        GG!!!!!!!!!'!!   \n");
        printf("      @@@@GG           TGG@@GGTTGTT!!TTGGGGGGGGGGGTT!!TTGTTGG@@GGT        @@@@@@GGG!!!!!!!!'!''!!  \n");
        printf("                        '!TTGGGTTTTT!!TTGGGGGGGGGTT!!TTTTTGGGTT!'             GGGTTTTTTTTTT!'!!'!! \n");
        printf("                            TTTTTGGTT!TTTTTGGGTTTTT!TTGGTTTTT                  GTTTTTTTTTTT'TT'!!! \n");
        printf("                                TTGTTTTTTTTTTTTTTTTTTTGTT                        TTTTTTTTTT!''!!!! \n");
        printf("                                   TTTTTGGTTTTTGGTTTTT                               !!!!!!!'!!!   \n");
        printf("                                        TGGGTGGGT                                       !!!!!!     \n");
        printf("                                                                                                   \n");
        Sleep(300);
        system("CLS");
        printf("                                                                                                   \n");
        printf("                                       TTTTTTTTTTT                                                 \n");
        printf("                              TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                      \n");
        printf("                       TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                 \n");
        printf("                    TTTTTTTTTTTTTTTTTGGGGGGGGGGGGGGGTTTTTTTTTTTTTTTTT                              \n");
        printf("                  TTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTTTTTTTTT                            \n");
        printf("                 TTTTTTTTGGGGGGGGGGGGGGG@@@@@@@@@GGGGGGGGGGGGGGGTTTTTTTT                           \n");
        printf("                 TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                           \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGTTTTTTT                          \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                         \n");
        printf("               TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGGGGTTTTTTTT                          \n");
        printf("               TTTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@GGGGGGGGGGGGGTTTTTTTT                          \n");
        printf("                TTTTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGTTTTTTTTTT                           \n");
        printf("                TTTTGGGGGGGGG!!!!!!!!!GGG@@@@@@GGG!!!!!!!!!!GGGGGGGGTTTT                           \n");
        printf("                TTTGGG!!!!!!!!!!!''''!!!GGGGGGGG!!!''''!!!!!!!!!!GGGGTTT                           \n");
        printf("                 'TGG!!!!!!!''''''''''!!!GGGGGG!!!'''''''''!!!!!!!GGGT'                            \n");
        printf("                 'TGG!!!!!'''''''''''''!!GG@@GG!!'''''''T''''!!!!!!!GG'                            \n");
        printf("                 ''TG@G!!!!''''''''''''!!!@@@@G!!'''''TT@TT'!!!!!!G@GT                             \n");
        printf("                   TG@G!!!!!!'''''''''!!!!@'@'@!!!''''''T'!!!!!!!!G@GT                             \n");
        printf("                   'TG@G!!!!!!!!!!!!!!GGG@''@''@GGG!!!!!!!!!!!!!!!G@GT'                            \n");
        printf("                  ''TG@G!!!!!!!!GGGGGGGGG@''G''@GGGGGGGGGG!!!!!!!!G@GT''                           \n");
        printf("                '''TTTG@@G!GGGGGGGGGGGTT@'''!'''@GGGGGGGGGGGGGGG!G@@GTTT'''                        \n");
        printf("               TTTGGGTTTGGGGGGGGTTTTTTGG@'''''''@GGTTTTGGGGGGGGGGGTTTGGGTTTT                       \n");
        printf("                TG@GTT!!TGGGGGTTTT!!!!TTG'''!'''GTTTTTTTTGGGGGGGT!!TTG@GT                          \n");
        printf("                  TTT!!!!!GG@GGTTT!!!!TT@'''T'''@GTTTTTGGGGG@GG!!!!!TTT                            \n");
        printf("                    ''!TGG@@@@@GGGT!!TTTTG''G''@GGTTGGGGGG@@@@@@GGT''                              \n");
        printf("                      TTTGGG@@''''G@GTTTGGGT@GGGGGGGGG''''@@GGGTTT                                 \n");
        printf("                       TTGGGG@''  !GGTTTGGGGGGGGGTTTGG!  ''@GGGGTT                                 \n");
        printf("                       TTGGGG@''  TGTTTGGGGGGGGGGGTTTGT  ''@GGGGTT               T                 \n");
        printf("                       TTTGGG@!'' GTG@T@@T@@T@@T@@T@GTG ''!@GGGTTT           TTTTTTT               \n");
        printf("                        TTGGG@G!' GTGG!G@T@@G@@T@G!GGTG '!G@GGGTT          TTTTTTTT!               \n");
        printf("                        TTGGG@G@@@@@@@TTGGT@G@TGGTT@@@@@@@G@GGGTT         GTTTT                    \n");
        printf("                    G@@@@@@@@@@GG!!TTGGGGG@@GGTG@@TGTT!!GG@@@@@@@@@G    GG'           !!!!!!       \n");
        printf("          @@@@@@@@@@@G TTGGG@GGGTT!!TTGGGGG@GGTG@GGTT!!TTGGG@GGGTTG@@@@@@@        GG!!!!!!!!!'!!   \n");
        printf("      @@@@GG           TGG@@GGTTGTT!!TTGGGGGGGGGGGTT!!TTGTTGG@@GGT        @@@@@@GGG!!!!!!!!'!''!!  \n");
        printf("                        '!TTGGGTTTTT!!TTGGGGGGGGGTT!!TTTTTGGGTT!'             GGGTTTTTTTTTT!'!!'!! \n");
        printf("                            TTTTTGGTT!TTTTTGGGTTTTT!TTGGTTTTT                  GTTTTTTTTTTT'TT'!!! \n");
        printf("                                TTGTTTTTTTTTTTTTTTTTTTGTT                        TTTTTTTTTT!''!!!! \n");
        printf("                                   TTTTTGGTTTTTGGTTTTT                               !!!!!!!'!!!   \n");
        printf("                                        TGGGTGGGT                                       !!!!!!     \n");
        printf("                                                                                                   \n");
        Sleep(300);
        system("CLS");
        printf("                                                                                                   \n");
        printf("                                       TTTTTTTTTTT                                                 \n");
        printf("                              TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                      \n");
        printf("                       TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                 \n");
        printf("                    TTTTTTTTTTTTTTTTTGGGGGGGGGGGGGGGTTTTTTTTTTTTTTTTT                              \n");
        printf("                  TTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTTTTTTTTT                            \n");
        printf("                 TTTTTTTTGGGGGGGGGGGGGGG@@@@@@@@@GGGGGGGGGGGGGGGTTTTTTTT                           \n");
        printf("                 TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                           \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGTTTTTTT                          \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                         \n");
        printf("               TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGGGGTTTTTTTT                          \n");
        printf("               TTTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@GGGGGGGGGGGGGTTTTTTTT                          \n");
        printf("                TTTTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGTTTTTTTTTT                           \n");
        printf("                TTTTGGGGGGGGG!!!!!!!!!GGG@@@@@@GGG!!!!!!!!!!GGGGGGGGTTTT                           \n");
        printf("                TTTGGG!!!!!!!!!!!''''!!!GGGGGGGG!!!''''!!!!!!!!!!GGGGTTT                           \n");
        printf("                 'TGG!!!!!!!''''''''''!!!GGGGGG!!!'''''''''!!!!!!!GGGT'                            \n");
        printf("                 'TGG!!!!!'''''''''''''!!GG@@GG!!'''''TTGTT''!!!!!!!GG'                            \n");
        printf("                 ''TG@G!!!!''''''''''''!!!@@@@G!!''''TTG@GTT!!!!!!G@GT                             \n");
        printf("                   TG@G!!!!!!'''''''''!!!!@'@'@!!!''''TTGTT!!!!!!!G@GT                             \n");
        printf("                   'TG@G!!!!!!!!!!!!!!GGG@''@''@GGG!!!!!!!!!!!!!!!G@GT'                            \n");
        printf("                  ''TG@G!!!!!!!!GGGGGGGGG@''G''@GGGGGGGGGG!!!!!!!!G@GT''                           \n");
        printf("                '''TTTG@@G!GGGGGGGGGGGTT@'''!'''@GGGGGGGGGGGGGGG!G@@GTTT'''                        \n");
        printf("               TTTGGGTTTGGGGGGGGTTTTTTGG@'''''''@GGTTTTGGGGGGGGGGGTTTGGGTTTT                       \n");
        printf("                TG@GTT!!TGGGGGTTTT!!!!TTG'''!'''GTTTTTTTTGGGGGGGT!!TTG@GT                          \n");
        printf("                  TTT!!!!!GG@GGTTT!!!!TT@'''T'''@GTTTTTGGGGG@GG!!!!!TTT                            \n");
        printf("                    ''!TGG@@@@@GGGT!!TTTTG''G''@GGTTGGGGGG@@@@@@GGT''                              \n");
        printf("                      TTTGGG@@''''G@GTTTGGGT@GGGGGGGGG''''@@GGGTTT                                 \n");
        printf("                       TTGGGG@''  !GGTTTGGGGGGGGGTTTGG!  ''@GGGGTT                                 \n");
        printf("                       TTGGGG@''  TGTTTGGGGGGGGGGGTTTGT  ''@GGGGTT               T                 \n");
        printf("                       TTTGGG@!'' GTG@T@@T@@T@@T@@T@GTG ''!@GGGTTT           TTTTTTT               \n");
        printf("                        TTGGG@G!' GTGG!G@T@@G@@T@G!GGTG '!G@GGGTT          TTTTTTTT!               \n");
        printf("                        TTGGG@G@@@@@@@TTGGT@G@TGGTT@@@@@@@G@GGGTT         GTTTT                    \n");
        printf("                    G@@@@@@@@@@GG!!TTGGGGG@@GGTG@@TGTT!!GG@@@@@@@@@G    GG'           !!!!!!       \n");
        printf("          @@@@@@@@@@@G TTGGG@GGGTT!!TTGGGGG@GGTG@GGTT!!TTGGG@GGGTTG@@@@@@@        GG!!!!!!!!!'!!   \n");
        printf("      @@@@GG           TGG@@GGTTGTT!!TTGGGGGGGGGGGTT!!TTGTTGG@@GGT        @@@@@@GGG!!!!!!!!'!''!!  \n");
        printf("                        '!TTGGGTTTTT!!TTGGGGGGGGGTT!!TTTTTGGGTT!'             GGGTTTTTTTTTT!'!!'!! \n");
        printf("                            TTTTTGGTT!TTTTTGGGTTTTT!TTGGTTTTT                  GTTTTTTTTTTT'TT'!!! \n");
        printf("                                TTGTTTTTTTTTTTTTTTTTTTGTT                        TTTTTTTTTT!''!!!! \n");
        printf("                                   TTTTTGGTTTTTGGTTTTT                               !!!!!!!'!!!   \n");
        printf("                                        TGGGTGGGT                                       !!!!!!     \n");
        printf("                                                                                                   \n");
        Sleep(300);
        system("CLS");
        printf("                                                                                                   \n");
        printf("                                       TTTTTTTTTTT                                                 \n");
        printf("                              TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                      \n");
        printf("                       TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                 \n");
        printf("                    TTTTTTTTTTTTTTTTTGGGGGGGGGGGGGGGTTTTTTTTTTTTTTTTT                              \n");
        printf("                  TTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTTTTTTTTT                            \n");
        printf("                 TTTTTTTTGGGGGGGGGGGGGGG@@@@@@@@@GGGGGGGGGGGGGGGTTTTTTTT                           \n");
        printf("                 TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                           \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGTTTTTTT                          \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                         \n");
        printf("               TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGGGGTTTTTTTT                          \n");
        printf("               TTTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@GGGGGGGGGGGGGTTTTTTTT                          \n");
        printf("                TTTTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGTTTTTTTTTT                           \n");
        printf("                TTTTGGGGGGGGG!!!!!!!!!GGG@@@@@@GGG!!!!!!!!!!GGGGGGGGTTTT                           \n");
        printf("                TTTGGG!!!!!!!!!!!''''!!!GGGGGGGG!!!''''!!!!!!!!!!GGGGTTT                           \n");
        printf("                 'TGG!!!!!!!''''''''''!!!GGGGGG!!!''''TTTT'!!!!!!!GGGT'                            \n");
        printf("                 'TGG!!!!!'''''''''''''!!GG@@GG!!'''TTGG@GGTT!!!!!!!GG'                            \n");
        printf("                 ''TG@G!!!!''''''''''''!!!@@@@G!!''TTGG@@@GGTT!!!!G@GT                             \n");
        printf("                   TG@G!!!!!!'''''''''!!!!@'@'@!!!''TTGG@GGTT!!!!!G@GT                             \n");
        printf("                   'TG@G!!!!!!!!!!!!!!GGG@''@''@GGG!!!!TTT!!!!!!!!G@GT'                            \n");
        printf("                  ''TG@G!!!!!!!!GGGGGGGGG@''G''@GGGGGGGGGG!!!!!!!!G@GT''                           \n");
        printf("                '''TTTG@@G!GGGGGGGGGGGTT@'''!'''@GGGGGGGGGGGGGGG!G@@GTTT'''                        \n");
        printf("               TTTGGGTTTGGGGGGGGTTTTTTGG@'''''''@GGTTTTGGGGGGGGGGGTTTGGGTTTT                       \n");
        printf("                TG@GTT!!TGGGGGTTTT!!!!TTG'''!'''GTTTTTTTTGGGGGGGT!!TTG@GT                          \n");
        printf("                  TTT!!!!!GG@GGTTT!!!!TT@'''T'''@GTTTTTGGGGG@GG!!!!!TTT                            \n");
        printf("                    ''!TGG@@@@@GGGT!!TTTTG''G''@GGTTGGGGGG@@@@@@GGT''                              \n");
        printf("                      TTTGGG@@''''G@GTTTGGGT@GGGGGGGGG''''@@GGGTTT                                 \n");
        printf("                       TTGGGG@''  !GGTTTGGGGGGGGGTTTGG!  ''@GGGGTT                                 \n");
        printf("                       TTGGGG@''  TGTTTGGGGGGGGGGGTTTGT  ''@GGGGTT               T                 \n");
        printf("                       TTTGGG@!'' GTG@T@@T@@T@@T@@T@GTG ''!@GGGTTT           TTTTTTT               \n");
        printf("                        TTGGG@G!' GTGG!G@T@@G@@T@G!GGTG '!G@GGGTT          TTTTTTTT!               \n");
        printf("                        TTGGG@G@@@@@@@TTGGT@G@TGGTT@@@@@@@G@GGGTT         GTTTT                    \n");
        printf("                    G@@@@@@@@@@GG!!TTGGGGG@@GGTG@@TGTT!!GG@@@@@@@@@G    GG'           !!!!!!       \n");
        printf("          @@@@@@@@@@@G TTGGG@GGGTT!!TTGGGGG@GGTG@GGTT!!TTGGG@GGGTTG@@@@@@@        GG!!!!!!!!!'!!   \n");
        printf("      @@@@GG           TGG@@GGTTGTT!!TTGGGGGGGGGGGTT!!TTGTTGG@@GGT        @@@@@@GGG!!!!!!!!'!''!!  \n");
        printf("                        '!TTGGGTTTTT!!TTGGGGGGGGGTT!!TTTTTGGGTT!'             GGGTTTTTTTTTT!'!!'!! \n");
        printf("                            TTTTTGGTT!TTTTTGGGTTTTT!TTGGTTTTT                  GTTTTTTTTTTT'TT'!!! \n");
        printf("                                TTGTTTTTTTTTTTTTTTTTTTGTT                        TTTTTTTTTT!''!!!! \n");
        printf("                                   TTTTTGGTTTTTGGTTTTT                               !!!!!!!'!!!   \n");
        printf("                                        TGGGTGGGT                                       !!!!!!     \n");
        printf("                                                                                                   \n");
        Sleep(300);
        system("CLS");
        printf("                                                                                                   \n");
        printf("                                       TTTTTTTTTTT                                                 \n");
        printf("                              TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                      \n");
        printf("                       TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                 \n");
        printf("                    TTTTTTTTTTTTTTTTTGGGGGGGGGGGGGGGTTTTTTTTTTTTTTTTT                              \n");
        printf("                  TTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTTTTTTTTT                            \n");
        printf("                 TTTTTTTTGGGGGGGGGGGGGGG@@@@@@@@@GGGGGGGGGGGGGGGTTTTTTTT                           \n");
        printf("                 TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                           \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGTTTTTTT                          \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                         \n");
        printf("               TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGGGGTTTTTTTT                          \n");
        printf("               TTTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@GGGGGGGGGGGGGTTTTTTTT                          \n");
        printf("                TTTTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGTTTTTTTTTT                           \n");
        printf("                TTTTGGGGGGGGG!!!!!!!!!GGG@@@@@@GGG!!!!!!!!!!GGGGGGGGTTTT                           \n");
        printf("                TTTGGG!!!!!!!!!!!''''!!!GGGGGGGG!!!''''!!!!!!!!!!GGGGTTT                           \n");
        printf("                 'TGG!!!!!!!''''''''''!!!GGGGGG!!!'''''''''!!!!!!!GGGT'                            \n");
        printf("                 'TGG!!!!!'''''''''''''!!GG@@GG!!'''''TTGTT''!!!!!!!GG'                            \n");
        printf("                 ''TG@G!!!!''''''''''''!!!@@@@G!!''''TTG@GTT!!!!!!G@GT                             \n");
        printf("                   TG@G!!!!!!'''''''''!!!!@'@'@!!!''''TTGTT!!!!!!!G@GT                             \n");
        printf("                   'TG@G!!!!!!!!!!!!!!GGG@''@''@GGG!!!!!!!!!!!!!!!G@GT'                            \n");
        printf("                  ''TG@G!!!!!!!!GGGGGGGGG@''G''@GGGGGGGGGG!!!!!!!!G@GT''                           \n");
        printf("                '''TTTG@@G!GGGGGGGGGGGTT@'''!'''@GGGGGGGGGGGGGGG!G@@GTTT'''                        \n");
        printf("               TTTGGGTTTGGGGGGGGTTTTTTGG@'''''''@GGTTTTGGGGGGGGGGGTTTGGGTTTT                       \n");
        printf("                TG@GTT!!TGGGGGTTTT!!!!TTG'''!'''GTTTTTTTTGGGGGGGT!!TTG@GT                          \n");
        printf("                  TTT!!!!!GG@GGTTT!!!!TT@'''T'''@GTTTTTGGGGG@GG!!!!!TTT                            \n");
        printf("                    ''!TGG@@@@@GGGT!!TTTTG''G''@GGTTGGGGGG@@@@@@GGT''                              \n");
        printf("                      TTTGGG@@''''G@GTTTGGGT@GGGGGGGGG''''@@GGGTTT                                 \n");
        printf("                       TTGGGG@''  !GGTTTGGGGGGGGGTTTGG!  ''@GGGGTT                                 \n");
        printf("                       TTGGGG@''  TGTTTGGGGGGGGGGGTTTGT  ''@GGGGTT               T                 \n");
        printf("                       TTTGGG@!'' GTG@T@@T@@T@@T@@T@GTG ''!@GGGTTT           TTTTTTT               \n");
        printf("                        TTGGG@G!' GTGG!G@T@@G@@T@G!GGTG '!G@GGGTT          TTTTTTTT!               \n");
        printf("                        TTGGG@G@@@@@@@TTGGT@G@TGGTT@@@@@@@G@GGGTT         GTTTT                    \n");
        printf("                    G@@@@@@@@@@GG!!TTGGGGG@@GGTG@@TGTT!!GG@@@@@@@@@G    GG'           !!!!!!       \n");
        printf("          @@@@@@@@@@@G TTGGG@GGGTT!!TTGGGGG@GGTG@GGTT!!TTGGG@GGGTTG@@@@@@@        GG!!!!!!!!!'!!   \n");
        printf("      @@@@GG           TGG@@GGTTGTT!!TTGGGGGGGGGGGTT!!TTGTTGG@@GGT        @@@@@@GGG!!!!!!!!'!''!!  \n");
        printf("                        '!TTGGGTTTTT!!TTGGGGGGGGGTT!!TTTTTGGGTT!'             GGGTTTTTTTTTT!'!!'!! \n");
        printf("                            TTTTTGGTT!TTTTTGGGTTTTT!TTGGTTTTT                  GTTTTTTTTTTT'TT'!!! \n");
        printf("                                TTGTTTTTTTTTTTTTTTTTTTGTT                        TTTTTTTTTT!''!!!! \n");
        printf("                                   TTTTTGGTTTTTGGTTTTT                               !!!!!!!'!!!   \n");
        printf("                                        TGGGTGGGT                                       !!!!!!     \n");
        printf("                                                                                                   \n");
        Sleep(300);
        system("CLS");
        printf("                                                                                                   \n");
        printf("                                       TTTTTTTTTTT                                                 \n");
        printf("                              TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                      \n");
        printf("                       TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                 \n");
        printf("                    TTTTTTTTTTTTTTTTTGGGGGGGGGGGGGGGTTTTTTTTTTTTTTTTT                              \n");
        printf("                  TTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTTTTTTTTT                            \n");
        printf("                 TTTTTTTTGGGGGGGGGGGGGGG@@@@@@@@@GGGGGGGGGGGGGGGTTTTTTTT                           \n");
        printf("                 TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                           \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGTTTTTTT                          \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                         \n");
        printf("               TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGGGGTTTTTTTT                          \n");
        printf("               TTTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@GGGGGGGGGGGGGTTTTTTTT                          \n");
        printf("                TTTTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGTTTTTTTTTT                           \n");
        printf("                TTTTGGGGGGGGG!!!!!!!!!GGG@@@@@@GGG!!!!!!!!!!GGGGGGGGTTTT                           \n");
        printf("                TTTGGG!!!!!!!!!!!''''!!!GGGGGGGG!!!''''!!!!!!!!!!GGGGTTT                           \n");
        printf("                 'TGG!!!!!!!''''''''''!!!GGGGGG!!!'''''''''!!!!!!!GGGT'                            \n");
        printf("                 'TGG!!!!!'''''''''''''!!GG@@GG!!'''''''T''''!!!!!!!GG'                            \n");
        printf("                 ''TG@G!!!!''''''''''''!!!@@@@G!!'''''TT@TT'!!!!!!G@GT                             \n");
        printf("                   TG@G!!!!!!'''''''''!!!!@'@'@!!!''''''T'!!!!!!!!G@GT                             \n");
        printf("                   'TG@G!!!!!!!!!!!!!!GGG@''@''@GGG!!!!!!!!!!!!!!!G@GT'                            \n");
        printf("                  ''TG@G!!!!!!!!GGGGGGGGG@''G''@GGGGGGGGGG!!!!!!!!G@GT''                           \n");
        printf("                '''TTTG@@G!GGGGGGGGGGGTT@'''!'''@GGGGGGGGGGGGGGG!G@@GTTT'''                        \n");
        printf("               TTTGGGTTTGGGGGGGGTTTTTTGG@'''''''@GGTTTTGGGGGGGGGGGTTTGGGTTTT                       \n");
        printf("                TG@GTT!!TGGGGGTTTT!!!!TTG'''!'''GTTTTTTTTGGGGGGGT!!TTG@GT                          \n");
        printf("                  TTT!!!!!GG@GGTTT!!!!TT@'''T'''@GTTTTTGGGGG@GG!!!!!TTT                            \n");
        printf("                    ''!TGG@@@@@GGGT!!TTTTG''G''@GGTTGGGGGG@@@@@@GGT''                              \n");
        printf("                      TTTGGG@@''''G@GTTTGGGT@GGGGGGGGG''''@@GGGTTT                                 \n");
        printf("                       TTGGGG@''  !GGTTTGGGGGGGGGTTTGG!  ''@GGGGTT                                 \n");
        printf("                       TTGGGG@''  TGTTTGGGGGGGGGGGTTTGT  ''@GGGGTT               T                 \n");
        printf("                       TTTGGG@!'' GTG@T@@T@@T@@T@@T@GTG ''!@GGGTTT           TTTTTTT               \n");
        printf("                        TTGGG@G!' GTGG!G@T@@G@@T@G!GGTG '!G@GGGTT          TTTTTTTT!               \n");
        printf("                        TTGGG@G@@@@@@@TTGGT@G@TGGTT@@@@@@@G@GGGTT         GTTTT                    \n");
        printf("                    G@@@@@@@@@@GG!!TTGGGGG@@GGTG@@TGTT!!GG@@@@@@@@@G    GG'           !!!!!!       \n");
        printf("          @@@@@@@@@@@G TTGGG@GGGTT!!TTGGGGG@GGTG@GGTT!!TTGGG@GGGTTG@@@@@@@        GG!!!!!!!!!'!!   \n");
        printf("      @@@@GG           TGG@@GGTTGTT!!TTGGGGGGGGGGGTT!!TTGTTGG@@GGT        @@@@@@GGG!!!!!!!!'!''!!  \n");
        printf("                        '!TTGGGTTTTT!!TTGGGGGGGGGTT!!TTTTTGGGTT!'             GGGTTTTTTTTTT!'!!'!! \n");
        printf("                            TTTTTGGTT!TTTTTGGGTTTTT!TTGGTTTTT                  GTTTTTTTTTTT'TT'!!! \n");
        printf("                                TTGTTTTTTTTTTTTTTTTTTTGTT                        TTTTTTTTTT!''!!!! \n");
        printf("                                   TTTTTGGTTTTTGGTTTTT                               !!!!!!!'!!!   \n");
        printf("                                        TGGGTGGGT                                       !!!!!!     \n");
        printf("                                                                                                   \n");
        Sleep(300);
        system("CLS");
        printf("                                                                                                   \n");
        printf("                                       TTTTTTTTTTT                                                 \n");
        printf("                              TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                      \n");
        printf("                       TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                 \n");
        printf("                    TTTTTTTTTTTTTTTTTGGGGGGGGGGGGGGGTTTTTTTTTTTTTTTTT                              \n");
        printf("                  TTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTTTTTTTTT                            \n");
        printf("                 TTTTTTTTGGGGGGGGGGGGGGG@@@@@@@@@GGGGGGGGGGGGGGGTTTTTTTT                           \n");
        printf("                 TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                           \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGTTTTTTT                          \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                         \n");
        printf("               TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGGGGTTTTTTTT                          \n");
        printf("               TTTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@GGGGGGGGGGGGGTTTTTTTT                          \n");
        printf("                TTTTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGTTTTTTTTTT                           \n");
        printf("                TTTTGGGGGGGGG!!!!!!!!!GGG@@@@@@GGG!!!!!!!!!!GGGGGGGGTTTT                           \n");
        printf("                TTTGGG!!!!!!!!!!!''''!!!GGGGGGGG!!!''''!!!!!!!!!!GGGGTTT                           \n");
        printf("                 'TGG!!!!!!!''''''''''!!!GGGGGG!!!'''''''''!!!!!!!GGGT'                            \n");
        printf("                 'TGG!!!!!'''''''''''''!!GG@@GG!!''''''''''''!!!!!!!GG'                            \n");
        printf("                 ''TG@G!!!!''''''''''''!!!@@@@G!!'''''''G'''!!!!!!G@GT                             \n");
        printf("                   TG@G!!!!!!'''''''''!!!!@'@'@!!!''''''''!!!!!!!!G@GT                             \n");
        printf("                   'TG@G!!!!!!!!!!!!!!GGG@''@''@GGG!!!!!!!!!!!!!!!G@GT'                            \n");
        printf("                  ''TG@G!!!!!!!!GGGGGGGGG@''G''@GGGGGGGGGG!!!!!!!!G@GT''                           \n");
        printf("                '''TTTG@@G!GGGGGGGGGGGTT@'''!'''@GGGGGGGGGGGGGGG!G@@GTTT'''                        \n");
        printf("               TTTGGGTTTGGGGGGGGTTTTTTGG@'''''''@GGTTTTGGGGGGGGGGGTTTGGGTTTT                       \n");
        printf("                TG@GTT!!TGGGGGTTTT!!!!TTG'''!'''GTTTTTTTTGGGGGGGT!!TTG@GT                          \n");
        printf("                  TTT!!!!!GG@GGTTT!!!!TT@'''T'''@GTTTTTGGGGG@GG!!!!!TTT                            \n");
        printf("                    ''!TGG@@@@@GGGT!!TTTTG''G''@GGTTGGGGGG@@@@@@GGT''                              \n");
        printf("                      TTTGGG@@''''G@GTTTGGGT@GGGGGGGGG''''@@GGGTTT                                 \n");
        printf("                       TTGGGG@''  !GGTTTGGGGGGGGGTTTGG!  ''@GGGGTT                                 \n");
        printf("                       TTGGGG@''  TGTTTGGGGGGGGGGGTTTGT  ''@GGGGTT               T                 \n");
        printf("                       TTTGGG@!'' GTG@T@@T@@T@@T@@T@GTG ''!@GGGTTT           TTTTTTT               \n");
        printf("                        TTGGG@G!' GTGG!G@T@@G@@T@G!GGTG '!G@GGGTT          TTTTTTTT!               \n");
        printf("                        TTGGG@G@@@@@@@TTGGT@G@TGGTT@@@@@@@G@GGGTT         GTTTT                    \n");
        printf("                    G@@@@@@@@@@GG!!TTGGGGG@@GGTG@@TGTT!!GG@@@@@@@@@G    GG'           !!!!!!       \n");
        printf("          @@@@@@@@@@@G TTGGG@GGGTT!!TTGGGGG@GGTG@GGTT!!TTGGG@GGGTTG@@@@@@@        GG!!!!!!!!!'!!   \n");
        printf("      @@@@GG           TGG@@GGTTGTT!!TTGGGGGGGGGGGTT!!TTGTTGG@@GGT        @@@@@@GGG!!!!!!!!'!''!!  \n");
        printf("                        '!TTGGGTTTTT!!TTGGGGGGGGGTT!!TTTTTGGGTT!'             GGGTTTTTTTTTT!'!!'!! \n");
        printf("                            TTTTTGGTT!TTTTTGGGTTTTT!TTGGTTTTT                  GTTTTTTTTTTT'TT'!!! \n");
        printf("                                TTGTTTTTTTTTTTTTTTTTTTGTT                        TTTTTTTTTT!''!!!! \n");
        printf("                                   TTTTTGGTTTTTGGTTTTT                               !!!!!!!'!!!   \n");
        printf("                                        TGGGTGGGT                                       !!!!!!     \n");
        printf("                                                                                                   \n");
        Sleep(300);
        system("CLS");
        printf("                                                                                                   \n");
        printf("                                       TTTTTTTTTTT                                                 \n");
        printf("                              TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                      \n");
        printf("                       TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                 \n");
        printf("                    TTTTTTTTTTTTTTTTTGGGGGGGGGGGGGGGTTTTTTTTTTTTTTTTT                              \n");
        printf("                  TTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTTTTTTTTT                            \n");
        printf("                 TTTTTTTTGGGGGGGGGGGGGGG@@@@@@@@@GGGGGGGGGGGGGGGTTTTTTTT                           \n");
        printf("                 TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                           \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGTTTTTTT                          \n");
        printf("                TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                          \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTT                         \n");
        printf("              TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                         \n");
        printf("               TTTTTTTGGGGGGGGGGG@@@@@@@@@@@@@@@@@@@@@@GGGGGGGGGGGTTTTTTT                          \n");
        printf("               TTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGGGGTTTTTTTT                          \n");
        printf("               TTTTTTTTGGGGGGGGGGGGG@@@@@@@@@@@@@@@@GGGGGGGGGGGGGTTTTTTTT                          \n");
        printf("                TTTTTTTTTGGGGGGGGGG@@@@@@@@@@@@@@@@@@GGGGGGGGGTTTTTTTTTT                           \n");
        printf("                TTTTGGGGGGGGG!!!!!!!!!GGG@@@@@@GGG!!!!!!!!!!GGGGGGGGTTTT                           \n");
        printf("                TTTGGG!!!!!!!!!!!''''!!!GGGGGGGG!!!''''!!!!!!!!!!GGGGTTT                           \n");
        printf("                 'TGG!!!!!!!''''''''''!!!GGGGGG!!!'''''''''!!!!!!!GGGT'                            \n");
        printf("                 'TGG!!!!!'''''''''''''!!GG@@GG!!''''''''''''!!!!!!!GG'                            \n");
        printf("                 ''TG@G!!!!''''''''''''!!!@@@@G!!'''''''''''!!!!!!G@GT                             \n");
        printf("                   TG@G!!!!!!'''''''''!!!!@'@'@!!!''''''''!!!!!!!!G@GT                             \n");
        printf("                   'TG@G!!!!!!!!!!!!!!GGG@''@''@GGG!!!!!!!!!!!!!!!G@GT'                            \n");
        printf("                  ''TG@G!!!!!!!!GGGGGGGGG@''G''@GGGGGGGGGG!!!!!!!!G@GT''                           \n");
        printf("                '''TTTG@@G!GGGGGGGGGGGTT@'''!'''@GGGGGGGGGGGGGGG!G@@GTTT'''                        \n");
        printf("               TTTGGGTTTGGGGGGGGTTTTTTGG@'''''''@GGTTTTGGGGGGGGGGGTTTGGGTTTT                       \n");
        printf("                TG@GTT!!TGGGGGTTTT!!!!TTG'''!'''GTTTTTTTTGGGGGGGT!!TTG@GT                          \n");
        printf("                  TTT!!!!!GG@GGTTT!!!!TT@'''T'''@GTTTTTGGGGG@GG!!!!!TTT                            \n");
        printf("                    ''!TGG@@@@@GGGT!!TTTTG''G''@GGTTGGGGGG@@@@@@GGT''                              \n");
        printf("                      TTTGGG@@''''G@GTTTGGGT@GGGGGGGGG''''@@GGGTTT                                 \n");
        printf("                       TTGGGG@''  !GGTTTGGGGGGGGGTTTGG!  ''@GGGGTT                                 \n");
        printf("                       TTGGGG@''  TGTTTGGGGGGGGGGGTTTGT  ''@GGGGTT               T                 \n");
        printf("                       TTTGGG@!'' GTG@T@@T@@T@@T@@T@GTG ''!@GGGTTT           TTTTTTT               \n");
        printf("                        TTGGG@G!' GTGG!G@T@@G@@T@G!GGTG '!G@GGGTT          TTTTTTTT!               \n");
        printf("                        TTGGG@G@@@@@@@TTGGT@G@TGGTT@@@@@@@G@GGGTT         GTTTT                    \n");
        printf("                    G@@@@@@@@@@GG!!TTGGGGG@@GGTG@@TGTT!!GG@@@@@@@@@G    GG'           !!!!!!       \n");
        printf("          @@@@@@@@@@@G TTGGG@GGGTT!!TTGGGGG@GGTG@GGTT!!TTGGG@GGGTTG@@@@@@@        GG!!!!!!!!!'!!   \n");
        printf("      @@@@GG           TGG@@GGTTGTT!!TTGGGGGGGGGGGTT!!TTGTTGG@@GGT        @@@@@@GGG!!!!!!!!'!''!!  \n");
        printf("                        '!TTGGGTTTTT!!TTGGGGGGGGGTT!!TTTTTGGGTT!'             GGGTTTTTTTTTT!'!!'!! \n");
        printf("                            TTTTTGGTT!TTTTTGGGTTTTT!TTGGTTTTT                  GTTTTTTTTTTT'TT'!!! \n");
        printf("                                TTGTTTTTTTTTTTTTTTTTTTGTT                        TTTTTTTTTT!''!!!! \n");
        printf("                                   TTTTTGGTTTTTGGTTTTT                               !!!!!!!'!!!   \n");
        printf("                                        TGGGTGGGT                                       !!!!!!     \n");
        printf("                                                                                                   \n");
        Sleep(300);
    }
     return 0;    
}

DWORD WINAPI InputThread(LPVOID data)
{
    const char ESC = 27;
    char input;
    while (1)
    {

        input = _getche();
        if (input == ESC)
        {
            quitting = true;
            break;
        }
    }
    return 0;
}